### ISSUE TITLE
grboard 구버전에서 업그레이드시 로그인문제

### ISSUE THREAD

**Issue by daebo01** [sirini/GR-Board#5]
정확한 버전은 기억나지 않으나... 기존해쉬가 MySQL password로 되어있더군요.
그래서 login_ok.php를 고치고 관리자 페이지에서 GR Board 업데이트를 했더니...
디비에 password 필드가 char(32)가 되서... 또 고쳤습니다.

**Comment by catgarret** [comment]
늦었지만,
password를 oldpassword로 바꿔주시면 계속 사용 가능하십니다.
